added a opening file to task file and corrected syntax error by adding word file
added file connection command to open task file. unfortunatly error came up need to check what synatx is wrong beteen line 4 and the opening connecting command line on line 8
---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
SyntaxError: expected ':' (<string>, line 4)